name: Update Missouri IPTV Playlist

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Build playlist
        run: node build-cvtv-playlist.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlists/missouri.m3u8

          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update Missouri IPTV playlist [skip ci]"

            # Retry push up to 3 times if remote has new commits
            for i in {1..3}; do
              git push origin main && break
              echo "Push rejected, pulling remote and retrying..."
              git pull --rebase origin main
            done
          else
            echo "No changes detected, skipping commit."
