name: Update Missouri IPTV Playlist

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours (00:00 and 12:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure playlists dir
        run: |
          mkdir -p playlists

      - name: Run update script
        run: |
          # Replace the line(s) below with your real playlist generation command(s).
          # Example: node build-evergreennow-m3u.js
          # Make sure your script writes output to playlists/missouri.m3u8
          echo "#EXTM3U" > playlists/missouri.m3u8

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add playlists/missouri.m3u8
          git diff --staged --quiet || git commit -m "Auto-update Missouri IPTV playlist [skip ci]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref_name || github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
