name: Update Missouri IPTV Playlist

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ensure playlists folder exists
        run: mkdir -p playlists

      - name: Install deps (no-op if no package.json)
        run: npm ci || true

      - name: Generate Missouri playlist
        run: node build-missouri-playlist.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlists/missouri.m3u8 || true
          git diff --cached --quiet || git commit -m "Auto-update Missouri IPTV playlist [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
