name: Update Missouri IPTV Playlist

# Run every 12 hours and allow manual trigger
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ensure playlists folder exists
        run: mkdir -p playlists

      - name: Install dependencies
        run: npm ci

      - name: Generate Missouri playlist
        run: |
          set -e
          node build-missouri-playlist.js > playlists/missouri.m3u8

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlists/missouri.m3u8
          git diff --cached --quiet || git commit -m "Auto-update Missouri IPTV playlist [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
