name: Update Missouri IPTV Playlist

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Build playlist
        run: node build-cvtv-playlist.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlists/missouri.m3u8
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update Missouri IPTV playlist [skip ci]"
            git pull --rebase origin main || true
            git push origin main
          else
            echo "No changes detected"
          fi
